# Generated by Django 2.2 on 2019-11-28 13:36

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_bannercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='needpay',
            field=models.BooleanField(default=False, verbose_name='是否付费课程'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情'),
        ),
    ]
