# Generated by Django 2.2 on 2019-12-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20191206_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
