# Generated by Django 2.2 on 2019-12-07 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20191206_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
