# Generated by Django 2.2 on 2019-12-07 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_video_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('qsone', models.CharField(max_length=100, verbose_name='题目1')),
                ('asone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, verbose_name='选项1')),
                ('jxone', models.CharField(max_length=100, verbose_name='解析1')),
                ('qstwo', models.CharField(max_length=100, verbose_name='题目2')),
                ('astwo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, verbose_name='选项2')),
                ('jxtwo', models.CharField(max_length=100, verbose_name='解析2')),
                ('qsthr', models.CharField(max_length=100, verbose_name='题目3')),
                ('asthr', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, verbose_name='选项3')),
                ('jxthr', models.CharField(max_length=100, verbose_name='解析3')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
            },
        ),
    ]
