# Generated by Django 2.2 on 2019-12-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_coursehomework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursehomework',
            options={'verbose_name': '课程作业', 'verbose_name_plural': '课程作业'},
        ),
    ]
