# Generated by Django 2.2 on 2019-12-07 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20191207_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehomework',
            name='asfive',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True, verbose_name='选项5'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='asfour',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True, verbose_name='选项4'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='jxfive',
            field=models.CharField(max_length=100, null=True, verbose_name='解析5'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='jxfour',
            field=models.CharField(max_length=100, null=True, verbose_name='解析4'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='qsfive',
            field=models.CharField(max_length=100, null=True, verbose_name='题目5'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='qsfour',
            field=models.CharField(max_length=100, null=True, verbose_name='题目4'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='asone',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True, verbose_name='选项1'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='asthr',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True, verbose_name='选项3'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='astwo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True, verbose_name='选项2'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='jxone',
            field=models.CharField(max_length=100, null=True, verbose_name='解析1'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='jxthr',
            field=models.CharField(max_length=100, null=True, verbose_name='解析3'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='jxtwo',
            field=models.CharField(max_length=100, null=True, verbose_name='解析2'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='qsone',
            field=models.CharField(max_length=100, null=True, verbose_name='题目1'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='qsthr',
            field=models.CharField(max_length=100, null=True, verbose_name='题目3'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='qstwo',
            field=models.CharField(max_length=100, null=True, verbose_name='题目2'),
        ),
    ]
