# Generated by Django 2.2 on 2019-12-07 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20191207_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehomework',
            name='asone',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, null=True, verbose_name='选项1'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='course',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='coursehomework',
            name='qsone',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='题目1'),
        ),
    ]
