# Generated by Django 2.2 on 2019-12-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20191207_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehomework',
            name='asfive',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, verbose_name='选项5'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='asfour',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, verbose_name='选项4'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='asthr',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, verbose_name='选项3'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='astwo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=2, verbose_name='选项2'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='jxfive',
            field=models.CharField(default='', max_length=100, verbose_name='解析5'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='jxfour',
            field=models.CharField(default='', max_length=100, verbose_name='解析4'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='jxthr',
            field=models.CharField(default='', max_length=100, verbose_name='解析3'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='jxtwo',
            field=models.CharField(default='', max_length=100, verbose_name='解析2'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='qsfive',
            field=models.CharField(default='', max_length=100, verbose_name='题目5'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='qsfour',
            field=models.CharField(default='', max_length=100, verbose_name='题目4'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='qsthr',
            field=models.CharField(default='', max_length=100, verbose_name='题目3'),
        ),
        migrations.AddField(
            model_name='coursehomework',
            name='qstwo',
            field=models.CharField(default='', max_length=100, verbose_name='题目2'),
        ),
    ]
