# Generated by Django 2.2 on 2019-12-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20191207_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursehomework',
            name='asfive',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='asfour',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='asone',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='asthr',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='astwo',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='jxfive',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='jxfour',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='jxone',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='jxthr',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='jxtwo',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='qsfive',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='qsfour',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='qsone',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='qsthr',
        ),
        migrations.RemoveField(
            model_name='coursehomework',
            name='qstwo',
        ),
    ]
