# Generated by Django 2.2 on 2019-12-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20191209_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursehomework',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='coursehomeworkdetail',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='讲师'),
        ),
    ]
