# Generated by Django 2.2 on 2019-12-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_course_is_classics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_classics',
        ),
    ]
