# Generated by Django 2.2 on 2019-12-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_remove_course_is_classics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerCourse',
        ),
    ]
