# Generated by Django 2.2 on 2019-12-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_delete_bannercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
    ]
