# Generated by Django 2.2 on 2019-11-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
