# Generated by Django 2.2 on 2019-12-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20191125_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userask',
            options={'verbose_name': '咨询', 'verbose_name_plural': '咨询'},
        ),
    ]
