# Generated by Django 2.2 on 2019-12-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20191210_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAsk',
        ),
    ]
