# Generated by Django 2.2 on 2019-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_delete_userask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '课程机构')], default=1, verbose_name='收藏类型'),
        ),
    ]
