# Generated by Django 2.2 on 2019-12-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20191128_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='is_auth',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='is_gold',
        ),
    ]
