# Generated by Django 2.2 on 2019-12-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_remove_courseorg_fav_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='click_nums',
        ),
    ]
