# Generated by Django 2.2 on 2019-12-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_remove_courseorg_click_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='students',
        ),
    ]
