# Generated by Django 2.2 on 2019-12-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_remove_courseorg_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_nums',
        ),
    ]
