# Generated by Django 2.2 on 2019-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_remove_courseorg_course_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(max_length=50, verbose_name='就职于'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='职位'),
        ),
    ]
