# Generated by Django 2.2 on 2019-12-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_auto_20191211_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='work_company',
        ),
    ]
