# Generated by Django 2.2 on 2019-12-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_remove_teacher_work_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='points',
        ),
    ]
