# Generated by Django 2.2 on 2019-12-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_remove_teacher_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='click_nums',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='fav_nums',
        ),
    ]
