# Generated by Django 2.2 on 2019-12-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20191211_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, null=True, verbose_name='性别'),
        ),
    ]
