# Generated by Django 2.2 on 2019-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
