# Generated by Django 2.2 on 2019-12-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_teacher_fav_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='address',
        ),
    ]
