# Generated by Django 2.2 on 2019-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_remove_courseorg_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校')], default='pxjg', max_length=4, verbose_name='机构类别'),
        ),
    ]
