# Generated by Django 2.2 on 2019-12-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_auto_20191212_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('gx', '高校'), ('pxjg', '培训机构')], default='pxjg', max_length=4, verbose_name='机构类别'),
        ),
    ]
